### ISSUE TITLE
Calling a curried constructor results in an error

### ISSUE THREAD

**Issue by Ashvin-Ranjan** [nbuilding/N-lang#129]
When calling a curried constructor like so:
```js
class SomeClass [a:int b:int] {
  // some code
}

let one = SomeClass(1)
let classInstace = one(4)
```
it will cause this error at runtime:
```
Traceback (most recent call last):
  File "n.py", line 84, in <module>
  File "asyncio\base_events.py", line 642, in run_until_complete
  File "n.py", line 56, in parse_tree
  File "scope.py", line 692, in eval_command
  File "scope.py", line 660, in eval_command
  File "scope.py", line 701, in eval_command
  File "scope.py", line 602, in eval_expr
  File "scope.py", line 623, in eval_expr
  File "scope.py", line 602, in eval_expr
  File "scope.py", line 496, in eval_expr
  File "scope.py", line 548, in eval_expr
  File "scope.py", line 602, in eval_expr
  File "scope.py", line 497, in eval_expr
  File "scope.py", line 619, in eval_expr
TypeError: 'NConstructor' object is not subscriptable
```

**Comment by Ashvin-Ranjan** [comment]
This appears to happen when an inbuilt function is called with the instance made with the curried contructor.

**Comment by Ashvin-Ranjan** [comment]
It appears that upon currying a constructor, something with the typing changes as it is curried incorrectly.
