### ISSUE TITLE
A function that returns an invalid value causes a runtime error during compile time

### ISSUE THREAD

**Issue by Ashvin-Ranjan** [nbuilding/N-lang#170]
When a function that has nothing returned is checked it ends up causing something similar to:
```
display_type was given a value that is neither a string nor a tuple nor a list nor a dictionary nor a NType. None
Traceback (most recent call last):
  File "C:\Users\Ashvin Ranjan\Desktop\N\main\python\n.py", line 104, in <module>
    error_count, warning_count = type_check(file, tree)
  File "C:\Users\Ashvin Ranjan\Desktop\N\main\python\n.py", line 49, in type_check
    scope.type_check_command(child)
  File "C:\Users\Ashvin Ranjan\Desktop\N\main\python\scope.py", line 1829, in type_check_command
    value_type = self.type_check_expr(value)
  File "C:\Users\Ashvin Ranjan\Desktop\N\main\python\scope.py", line 1333, in type_check_expr
    check_type = self.type_check_expr(argument)
  File "C:\Users\Ashvin Ranjan\Desktop\N\main\python\scope.py", line 1276, in type_check_expr
    returnvalue = scope.type_check_command(codeblock)
  File "C:\Users\Ashvin Ranjan\Desktop\N\main\python\scope.py", line 1675, in type_check_command
    exit = self.type_check_command(instruction)
  File "C:\Users\Ashvin Ranjan\Desktop\N\main\python\scope.py", line 1818, in type_check_command
    display_type(return_type),
  File "C:\Users\Ashvin Ranjan\Desktop\N\main\python\type_check_error.py", line 92, in display_type
    display += "[%s]" % ", ".join(
  File "C:\Users\Ashvin Ranjan\Desktop\N\main\python\type_check_error.py", line 93, in <genexpr>
    display_type(typevar, False) for typevar in n_type.typevars
  File "C:\Users\Ashvin Ranjan\Desktop\N\main\python\type_check_error.py", line 76, in display_type
    "(" + ", ".join(display_type(type, False) for type in n_type) + ")"
  File "C:\Users\Ashvin Ranjan\Desktop\N\main\python\type_check_error.py", line 76, in <genexpr>
    "(" + ", ".join(display_type(type, False) for type in n_type) + ")"
  File "C:\Users\Ashvin Ranjan\Desktop\N\main\python\type_check_error.py", line 103, in display_type
    raise TypeError("found None")
TypeError: found None
```
An example of something that triggered this was:
```js
let pub generateLegalMoves = [p:piece board:list[(int, color)], enPassantSquare:maybe[(int, int)]] -> list[((int, int), bool)] {
	let pieceType, pieceColor = piece
	let out = ""

	if (pieceType == 1) {
		var out = "P"
	} else if (pieceType == 2) {
		var out = "N"
	} else if (pieceType == 3) {
		var out = "B"
	} else if (pieceType == 4) {
		var out = "R"
	} else if (pieceType == 5) {
		var out = "Q"
	}
}
```
## EDIT
After more checking this appears to be the offending code
```js
let board:list[(int, piece.color)] = range(0, 64, 1)
                                                   |> filterMap([_:int] -> maybe[int] { return yes((0, piece.white)) })
```
here is the enum
```js
type pub color = white
               | black
```

**Comment by SheepTester** [comment]
Hmm, is there a simpler case that triggers this? Such as

```ts
let test = [a:int] -> str {
  let out = ""
  if a == 1 {
    var out = "2"
  }
}
```

Or maybe it's that return type specifically:
```ts
let test2 = [a: int] -> list[((int, int), bool)] {
  print("I do nothing!")
}
```

I haven't tested these

**Comment by SheepTester** [comment]
It's quite odd because `display_type(return_type),` occurs when type-checking `return`, but there's no return statement in your function. Are you sure it's due to that?

https://github.com/nbuilding/N-lang/blob/5d9e50af47cc1f0fd14b434997a97fc764e8cca8/python/scope.py#L1812-L1822

Do you think it would help if we could make it detect in which Token the error came from and use that to make a fancy error like is done for type errors and syntax errors?

**Comment by Ashvin-Ranjan** [comment]
After investigation
```js
let test = [] -> str {
}
```
causes
```
Error: The function return type of a str is unable to support the default return of () [maybe you forgot a return].
  --> run.n:1:22
1 | let test = [] -> str {
2 | }
Ran with 1 error and 0 warnings
```

```js
let test = [] -> list[((int, int), bool)] {
}
```
causes
```
Error: The function return type of a list[((int, int), bool)] is unable to support the default return of () [maybe you forgot a return].
  --> run.n:1:43
1 | let test = [] -> list[((int, int), bool)] {
2 | }
Ran with 1 error and 0 warnings
```

```js
let test = [a:int] -> str {
  let out = ""
  if a == 1 {
    var out = "2"
  }
}
```
causes
```
Error: The function return type of a str is unable to support the default return of () [maybe you forgot a return].
  --> run.n:1:27
1 | let test = [a:int] -> str {
2 |   let out = ""
3 |   if a == 1 {
4 |     var out = "2"
5 |   }
6 | }
Ran with 1 error and 0 warnings
```
and
```js
let test = [a:int] -> str {
	let out = ""
	if a == 1 {
		var out = "2"
	} else if a == 2 {
		var out = "3"
	}
}
```
causes
```
Error: The function return type of a str is unable to support the default return of () [maybe you forgot a return].
  --> run.n:1:27
1 | let test = [a:int] -> str {
2 |     let out = ""
3 |     if a == 1 {
4 |         var out = "2"
5 |     } else if a == 2 {
6 |         var out = "3"
7 |     }
8 | }
Ran with 1 error and 0 warnings
```
and even without the `let` the last examples work fine

**Comment by Ashvin-Ranjan** [comment]
After more checking this appears to be the offending code
```js
let board:list[(int, piece.color)] = range(0, 64, 1)
                                                   |> filterMap([_:int] -> maybe[int] { return yes((0, piece.white)) })
```

**Comment by SheepTester** [comment]
maybe it can't figure out the type of `piece.white` or something? idk

**Comment by Ashvin-Ranjan** [comment]
Hmm maybe, it's an enum thing of piece.color so I don't know why it would be `None`

**Comment by Ashvin-Ranjan** [comment]
After more investigation it appears that the value being passed into `display_type` is `NTypeVars('maybe', [['int', None]])`, which means the enum is getting evaluated to `None` because it is not defined, as it was never made public. therefore causing it to return `None` and `display_type` to fail

**Comment by SheepTester** [comment]
hmm, so might that be an issue with record access?

**Comment by Ashvin-Ranjan** [comment]
> hmm, so might that be an issue with record access?

No, this appears to be with anything, like unknown variables, as their type in `type_check_expr` is `None`

**Comment by SheepTester** [comment]
Ah, I see, that makes sense

I think the tuple type is supposed to detect None and then return None if the type contains a None, but I have since revised the type system to be more intelligent, so perhaps we can make display_type display None as `...` or something
