### ISSUE TITLE
Program does not exit quietly sometimes

### ISSUE THREAD

**Issue by Ashvin-Ranjan** [nbuilding/N-lang#297]
This usually happens during an `cmd` function:
```
Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<Function.run.<locals>.run_command() running at function.py:47> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x000001BA147FB9A0>()]> cb=[<TaskWakeupMethWrapper object at 0x000001BA1479CE50>()]>
Task was destroyed but it is pending!
task: <Task pending name='Task-403' coro=<Function.run.<locals>.run_command() running at function.py:47> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x000001BA149418B0>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-426' coro=<Function.run.<locals>.run_command() running at function.py:47> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x000001BA1495DDF0>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-419' coro=<Function.run.<locals>.run_command() running at function.py:47> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x000001BA148E6160>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-411' coro=<Function.run.<locals>.run_command() running at function.py:47> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x000001BA148E6460>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-1066' coro=<Function.run.<locals>.run_command() done, defined at function.py:45> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x000001BA1492D8E0>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-1071' coro=<Function.run.<locals>.run_command() done, defined at function.py:45> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x000001BA148D4F10>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-1075' coro=<Function.run.<locals>.run_command() done, defined at function.py:45> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x000001BA1492B6D0>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-1079' coro=<Function.run.<locals>.run_command() done, defined at function.py:45> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x000001BA148EBBE0>()]>>
Task exception was never retrieved
future: <Task finished name='Task-1085' coro=<Function.run.<locals>.run_command() done, defined at function.py:45> exception=KeyboardInterrupt()>
Traceback (most recent call last):
  File "n.py", line 212, in <module>
  File "n.py", line 136, in run_file
  File "asyncio\base_events.py", line 629, in run_until_complete
  File "asyncio\windows_events.py", line 316, in run_forever
  File "asyncio\base_events.py", line 596, in run_forever
  File "asyncio\base_events.py", line 1890, in _run_once
  File "asyncio\events.py", line 80, in _run
  File "function.py", line 47, in run_command
  File "scope.py", line 1289, in eval_command
  File "scope.py", line 1326, in eval_command
  File "scope.py", line 1289, in eval_command
  File "scope.py", line 1370, in eval_command
  File "scope.py", line 985, in eval_expr
  File "scope.py", line 985, in eval_expr
  File "scope.py", line 986, in eval_expr
  File "scope.py", line 1021, in eval_expr
  File "scope.py", line 1135, in eval_expr
  File "scope.py", line 956, in eval_expr
  File "codecs.py", line 309, in __init__
KeyboardInterrupt
Task was destroyed but it is pending!
task: <Task pending name='Task-862' coro=<Function.run.<locals>.run_command() running at function.py:47> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x000001BA148B9FA0>()]>>
```

**Comment by Ashvin-Ranjan** [comment]
From what I can tell this is an issue with the library we are using, I am marking this as closed for now until a fix with it comes out.
